#define SPU_COMMAND_NOP 1
#define SPU_COMMAND_JUMP 2
#define SPU_COMMAND_ADD_CHILD 3
#define SPU_COMMAND_DELETE_CHILD 4
#define SPU_COMMAND_GL_BEGIN 5
#define SPU_COMMAND_GL_END 6
#define SPU_COMMAND_GL_VERTEX3 7
